name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    staging:
      +schema: stg
      +materialized: table
    intermediate:
      +schema: int
      +materialized: table
    marts:
      +schema: int
      +materialized: table

seeds:
  dbt_project:
    +schema: seeds

snapshots:
  dbt_project:
    +schema: snap

data_tests:
  +store_failures: true